#!/bin/bash
sudo clear
echo -e "\033[33m"

echo "###################################################"
echo "## DV-MEGA LTD GENESIS OLED SCREEN SAVER INSTALL ##"
echo "###################################################"
read -p " "
echo -e "\033[31m    YOUR SYSTEM MUST BE IN READWRITE MODE"
echo -e "if not the case, please press ctrl-c to stop"
echo -e "\033[33m    else press ENTER to start the process"
read -p ""
#sudo rpi-rw
sleep 1
echo -e "---> Stopping MMDVMHost service\n"
sudo systemctl stop mmdvmhost
sleep 1
if [ ! -f /usr/local/bin/MMDVMHost.original ] ; then
  echo -e "---> Backing up existing MMDVMHost binary to MMDVMHost.original\n"
  sudo cp /usr/local/bin/MMDVMHost /usr/local/bin/MMDVMHost.original
fi
sleep 1
echo -e "---> Copying the new MMDVMHost\n"
sudo cp MMDVMHost /usr/local/bin/MMDVMHost
sleep 1
echo -e "---> Now restarting MMDVMHost service\n"
sudo systemctl start mmdvmhost
sleep 1
echo -e "---> The system is now updated\n"
sleep 2
echo -e "\033[31m"
echo "Remember that if you do a pistar-update & pistar-upgrade you will loose the DV-MEGA LTD screen saver !"
echo -e "\033[33mGood trafic with the GENESIS NODE\n"

